name: Homelab CI

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Root Docker Compose
        run: docker compose -f docker-compose.yml config

      - name: Validate Monitoring Docker Compose
        run: docker compose -f monitoring/docker-compose.yml config
